#!/bin/bash
# Custom Firewall Drop Script for Wazuh
# Template Generated by Copilot
# Last Modified by Maxwell Klema on August 11th, 2025
# ---------------------------------------------------

# Usage: This script reads JSON input from STDIN
# Expected JSON format:
# {
#   "version": 1,
#   "command": "add|delete", 
#   "parameters": {
#     "alert": {
#       "data": {
#         "srcip": "IP_ADDRESS"
#       }
#     }
#   }
# }
# Full list: https://documentation.wazuh.com/current/user-manual/capabilities/active-response/custom-active-response-scripts.html

# Set script name for logging
LOG_FILE="/var/ossec/logs/active-responses.log"

# Function to log messages
log_message() {
    echo "[$(date '+%Y/%m/%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

# Read JSON input from STDIN
read -r INPUT

# Parse JSON to extract command and srcip
COMMAND=$(echo "$INPUT" | jq -r '.command // empty')
SRCIP=$(echo "$INPUT" | jq -r '.parameters.alert.data.srcip // empty')

# Validate input
if [[ -z "$COMMAND" || -z "$SRCIP" ]]; then
    log_message "ERROR: Invalid input - missing command or srcip"
    exit 1
fi

# Validate IP address format
if ! [[ "$SRCIP" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    log_message "ERROR: Invalid IP address format: $SRCIP"
    exit 1
fi

# Function to add firewall rule
add_rule() {
    local ip="$1"

    if ! iptables -C INPUT -s "$ip" -j DROP 2>/dev/null; then
        log_message "Adding INPUT firewall rule to block $ip"
        iptables -I INPUT -s "$ip" -j DROP 2>/dev/null
    fi 

    if ! iptables -C FORWARD -s "$ip" -j DROP 2>/dev/null; then
        log_message "Adding FORWARDfirewall rule to block $ip"
        iptables -I FORWARD -s "$ip" -j DROP 2>/dev/null
    fi 
}

# Function to remove firewall rule
remove_rule() {
    local ip="$1"
    log_message "Removing firewall rule for $ip"
    
    # Remove iptables rules
    iptables -D INPUT -s "$ip" -j DROP 2>/dev/null
    if [[ $? -eq 0 ]]; then
        log_message "Successfully removed INPUT rule for $ip"
    else
        log_message "WARNING: INPUT rule for $ip may not exist or already removed"
    fi
    
    iptables -D FORWARD -s "$ip" -j DROP 2>/dev/null
    if [[ $? -eq 0 ]]; then
        log_message "Successfully removed FORWARD rule for $ip"
    else
        log_message "WARNING: FORWARD rule for $ip may not exist or already removed"
    fi
}

# Execute based on command
case "$COMMAND" in
    "add")
        add_rule "$SRCIP"
        ;;
    "delete")
        remove_rule "$SRCIP"
        ;;
    *)
        log_message "ERROR: Unknown command: $COMMAND"
        exit 1
        ;;
esac

exit 0
