#!/bin/bash
# Custom Firewall Drop Script for Wazuh
# Template Generated by Copilot
# Last Modified by Maxwell Klema on August 11th, 2025
# ---------------------------------------------------

# Usage: This script reads JSON input from STDIN
# Expected JSON format:
# {
#   "version": 1,
#   "command": "add|delete",
#   "parameters": {
#     "alert": {
#       "data": {
#         "srcip": "IP_ADDRESS"
#       }
#     }
#   }
# }
# Full list: https://documentation.wazuh.com/current/user-manual/capabilities/active-response/custom-active-response-scripts.html

# Set script name for logging
LOG_FILE="/var/ossec/logs/active-responses.log"

# Function to log messages
log_message() {
    echo "[$(date '+%Y/%m/%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

# Read JSON input from STDIN
read -r INPUT

# Parse JSON to extract command and srcip
COMMAND=$(echo "$INPUT" | jq -r '.command // empty')
SRCIP=$(echo "$INPUT" | jq -r '.parameters.alert.data.srcip // empty')

# Validate input
if [[ -z "$COMMAND" || -z "$SRCIP" ]]; then
    log_message "ERROR: Invalid input - missing command or srcip"
    exit 1
fi

# Validate IP address format
if ! [[ "$SRCIP" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    log_message "ERROR: Invalid IP address format: $SRCIP"
    exit 1
fi

# Function to add firewall rule
add_rule() {
    local ip="$1"
    ipset add blacklist "$ip" 2>/dev/null
    if [[ $? -eq 0 ]]; then
        log_message "Successfully added $ip to blacklist"
    else
        log_message "WARNING: Failed to add $ip to blacklist or it may already exist"
    fi
}

# Function to remove firewall rule
remove_rule() {
    local ip="$1"

    ipset del blacklist "$ip" 2>/dev/null
    if [[ $? -eq 0 ]]; then
        log_message "Successfully removed $ip from blacklist"
    else
        log_message "WARNING: Failed to remove $ip from blacklist or it may not exist"
    fi
}

# Execute based on command
case "$COMMAND" in
    "add")
        add_rule "$SRCIP"
        ;;
    "delete")
        remove_rule "$SRCIP"
        ;;
    *)
        log_message "ERROR: Unknown command: $COMMAND"
        exit 1
        ;;
esac

exit 0