[Unit]
ConditionPathExists=|/etc/sssd/sssd.conf.template

[Service]
EnvironmentFile=-/etc/environment
ExecStartPre=+-/bin/sh -c "umask 0226 && /bin/envsubst </etc/sssd/sssd.conf.template >/etc/sssd/sssd.conf"
